CBTAPP/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('accounts.urls', namespace= 'accounts')),
    path('student/',include('student.urls', namespace='student')),
    path('lecturer/',include('lecturer.urls', namespace='lecturer')),
    path('test/', include('cbt.urls', namespace= 'cbt')),
    path('admin/', admin.site.urls),
]

cbt/urls.py
from django.urls import path 
from .views import * 

app_name = 'cbt'

urlpatterns = [ 
    path('take_quiz/<int:pk>/', take_quiz, name = 'take_quiz'),
]

student/urls.py
from django.urls import path
from .views import *

app_name = 'student'

urlpatterns = [
    path('dashboard/',dashboard, name ='dashboard' ),
    path('view_subjects/', viewSubjects, name = 'view_subjects'),
    # path('<str:subject_name>/view_grade/',viewSubjectGrade, name ='view_subject_grade'),
    # path('/subject/<str:subject_name>/view_grade/', viewSubjectGrade, name ='view_subject_grade')
]

student/models.py
from django.db import models


from lecturer.models import Subject
from accounts.models import User


# ! Account and Authentication yet to be added
class Student(models.Model):
    level_choices = [("ND1", "ND1"), ("ND2", "ND2"), ("ND3", "ND3"),
                     ("HND1", "HND1"), ("HND2", "HND2"), ("HND3", "HND3")]
    session_type_choices = [("Full-Time", "Full-Time"),
                            ("Part-Time", "Part-Time")]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    surname = models.CharField(max_length=25)
    first_name = models.CharField(max_length=25)
    other_name = models.CharField(max_length=25)
    email = models.EmailField(max_length=100)
    matric_no = models.CharField(max_length=25, null=False)
    session_type = models.CharField(
        choices=session_type_choices, max_length=15, null=False, blank=False)
    level = models.CharField(choices=level_choices,
                             max_length=4, null=False, blank=False)
    # ? related name to access students from subject object
    subjects = models.ManyToManyField(Subject, related_name='students')

    def __str__(self):
        return f"{self.surname} {self.first_name}"

student/forms.py
from django import forms
from django.db import transaction

from .models import Student
from accounts.models import User
from lecturer.models import Subject


class StudentCreationForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['surname', 'first_name', 'other_name', 'email',
                  'matric_no', 'subjects', 'session_type', 'level']
        widgets = {
            'subjects': forms.CheckboxSelectMultiple
        }

    @transaction.atomic
    def save(self):
        student = super().save(commit=False)
        user = User.objects.create_user(username=self.cleaned_data.get('matric_no'), email=self.cleaned_data.get(
            'email'), password=self.cleaned_data.get('surname'), type='student')
        subjects = self.cleaned_data.get('subjects')
        user.save()
        student.user = user
        student.save()
        for subject in subjects:
            student.subjects.add(subject)
        student.save()

student/views.py
from django.shortcuts import render
from cbt.models import Subject, TestResult, QuizList
from .models import Student
from django.contrib.auth.decorators import login_required


@login_required
def dashboard(request):
    student = Student.objects.get(user=request.user)
    students_quizzes = [quizlist.quiz for quizlist in QuizList.objects.all(
    ) if student in quizlist.candidates.all()]
    all_quizzes_count = len(students_quizzes)
    completed_quizzes_results = student.quiz_results.all()
    completed_quizzes = []
    if len(completed_quizzes_results) > 0:
        completed_quizzes = [
            result.quiz for result in completed_quizzes_results]
    completed_quizzes_count = len(completed_quizzes)
    uncompleted_quizzes = []
    if completed_quizzes_count < len(students_quizzes):
        uncompleted_quizzes = [
            quiz for quiz in students_quizzes if quiz not in completed_quizzes]
    uncompleted_quizzes_count = all_quizzes_count - completed_quizzes_count
    context = {"student": student, 'student_quizzes': students_quizzes, 'all_quizzes_count': all_quizzes_count,
               'completed_quizzes': completed_quizzes, 'completed_quizzes_count': completed_quizzes_count, 'uncompleted_quizzes': uncompleted_quizzes, 'uncompleted_quizzes_count':uncompleted_quizzes_count}
    return render(request, 'student/dashboard.html', context)


@login_required
def viewSubjects(request):
    student = Student.objects.get(user=request.user)
    subjects = student.subjects
    return render(request, 'student/subjects.html', context={'subjects': subjects})

templates/student/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=`, initial-scale=1.0" />
    <title>Home</title>
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static '/css/all.css' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/base.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/layouts.css' %}"
    />
    <link rel="icon" href="{% static '/images/logo.png' %}" />
  </head>

  <body>
    <div class="row">
      <aside class="col-md-2 position-fixed aside">
        <ul class="side-nav__nav">
          <li>
            <a class="side-nav__link" href="{% url 'student:dashboard' %}"
              >Your Dashboard</a
            >
          </li>
        </ul>
      </aside>
      <main class="offset-md-2 col-md-10">
        <nav>
          <div>
            {% if student.user.is_authenticated %}
            <h2>Welcome {{ student.surname }} {{student.first_name }}</h2>
            {% endif %}
          </div>
        </nav>
        <div class="content">{% block content %} {% endblock content %}</div>
      </main>
    </div>
  </body>
</html>

templates/student/dashboard.html
{% extends 'student/base.html' %} {% block content %}
<section>
  <h3>Quiz Information</h3>
  <div class="quiz_info_container">
    <div class="card">
      <h4>All Quizzes</h4>
      <h5>{{all_quizzes_count}}
    </div>
    <div class="card">
      <h4>Completed Quizzes</h4>
      <h5>{{completed_quizzes_count}}
    </div>
    <div class="card">
      <h4>Remaining Quizzes</h4>
      <h5>{{uncompleted_quizzes_count}}</h5>
    </div>
  </div>
</section>

<section>
  <h3>Completed quizzes</h3>
  <div class="quiz_info_container">
    {% for quiz in completed_quizzes %}
      <div class="card">
        <h4>{{quiz.title}}</h4>
        <p>{{quiz.description}}</p>
      </div>
    {% endfor %}
  </div>
</section>

<section>
  <h3>Remaining quizzes</h3>
  <div class="quiz_info_container">
    {% for quiz in uncompleted_quizzes %}
      <div class="card">
        <h4>{{quiz.title}}</h4>
        <p>{{quiz.description}}</p>
        <a href="{% url 'cbt:take_quiz' quiz.pk %}" class="btn btn-success">Take Quiz</a>
      </div>
    {% endfor %}
  </div>
</section>

{% endblock content %}

templates/student/subjects.html
{% extends 'student/base.html' %} {% block content %}
<section class="table-responsive px-3">
    <h3>List of Registered Courses</h3>
        <table class="table text-center">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Lecturer</th>
                </tr>
            </thead>
            <tbody>
                {% for subject in subjects.all %}
                <tr>
                    <td>{{ subject.title }}</td>
                    <td>{{subject.lecturer}}</td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
</section>
{% endblock content %}