CBTAPP/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('accounts.urls', namespace= 'accounts')),
    path('student/',include('student.urls', namespace='student')),
    path('lecturer/',include('lecturer.urls', namespace='lecturer')),
    path('test/', include('cbt.urls', namespace= 'cbt')),
    path('admin/', admin.site.urls),
]

cbt/urls.py
from django.urls import path 
from .views import * 

app_name = 'cbt'

urlpatterns = [ 
    path('take_quiz/<int:pk>/', take_quiz, name = 'take_quiz'),
]

cbt/models.py
from django.db import models
from lecturer.models import Subject
from student.models import Student


class Quiz(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, related_name="quizzes", null=False)


class QuizList(models.Model):
    quiz = models.ForeignKey(
        Quiz, on_delete=models.CASCADE, related_name="quiz_canditates", null=False)
    candidates = models.ManyToManyField(Student)


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)


class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)
    order = models.IntegerField(default=0)


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answered_by = models.ForeignKey(Student, on_delete=models.CASCADE)
    option = models.ForeignKey(Option, on_delete=models.CASCADE)


class TestResult(models.Model):
    quiz = models.ForeignKey(
        Quiz, on_delete=models.CASCADE, related_name='quiz_results')
    score = models.IntegerField(default=0)
    student = models.ForeignKey(
        Student, on_delete=models.CASCADE, related_name='quiz_results')

cbt/forms.py
from django.forms import ModelForm, Form, TextInput,Textarea,Select,CharField,ModelChoiceField
from .models import Quiz
from lecturer.models import Subject


class QuizCreationForm(ModelForm):
    title=CharField(widget=TextInput(attrs={'class':'form-control'}))
    description=CharField(widget=Textarea(attrs={'class':'form-control'}))
    class Meta:
        model = Quiz
        fields = ("title", "description")
        

cbt/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from .models import Quiz, Question, Option, Answer, TestResult
from student.models import Student
from lecturer.models import Subject
from django.contrib.auth.decorators import login_required
import logging


logger = logging.getLogger('django')


@login_required
def take_quiz(request, pk):
    student = Student.objects.get(user=request.user)
    quiz = Quiz.objects.get(pk=pk)
    if request.method == "GET":
        if student.quiz_results.all().count() > 0:
            for quiz_result in student.quiz_results.all():
                if quiz_result.quiz == quiz:
                    return redirect(reverse("student:dashboard"))
                else:
                    questions = quiz.question_set.all()
                    return render(request, 'cbt/take_test.html', {'quiz': quiz, 'questions': questions})
        else:
            questions = quiz.question_set.all()
            return render(request, 'cbt/take_test.html', {'quiz': quiz, 'questions': questions})

    elif request.method == 'POST':
        data = request.POST
        correct_answer_count = 0
        for x, y in data.items():
            if x == "csrfmiddlewaretoken":
                continue
            elif x == "quiz_id":
                quiz = Quiz.objects.get(id=int(y))
            else:
                option = Option.objects.get(id=int(y))
                question = Question.objects.get(id=int(x))
                answer = Answer(question=question,
                                option=option, answered_by=student)
                answer.save()
                if answer.option.is_correct == True:
                    correct_answer_count += 1
        test_result = TestResult(quiz=quiz,
                                 score=correct_answer_count,  student=student)
        test_result.save()
        return redirect(reverse("student:dashboard"))


@login_required
def handleTestSubmit(request):
    """ score = 0
    if request.method == 'POST':
        data = request.POST
        questions = Question.objects.filter(subject__title = data['subject_title']).order_by('id')
        for q in questions:
            if q.text  in data.keys():
                choice = data[q.text]
                if choice == q.answer:
                    score += 1
        test_result = TestResult.objects.create(
            subject = Subject.objects.get(title = data['subject_title']),
            score = score,
            student = Student.objects.get(user = request.user)
        )
        test_result.save()
        return redirect('student:dashboard')
    return redirect('student:dashboard') """
    return HttpResponse("Test Submitted")

templates/cbt/take_test.html
{% extends 'student/base.html' %} {% block content %}
<h2>{{quiz.title}}</h2>
<h4>{{quiz.description}}</h4>

<form method="post">
  {% csrf_token %}
  <input type="number" name="quiz_id"  value="{{quiz.pk}}" hidden/>
  {% for question in questions %}
  <p>{{question.text}}</p>
  <div>
    {% for option in question.option_set.all %}
    <input type="radio" name="{{question.id}}" value="{{option.id}}" />
    <span>{{option.text}}</span>
    {% endfor %}
  </div>
  {% endfor %}

  <button type="submit" class="btn btn-success">Finish Attempt</button>
</form>
{% endblock content %}

templates/cbt/test.html
{% extends 'student/base.html' %} 

{% block content %}
<h2>  {{ subject }} Test </h2>
<div class="container">
    {% if questions.all %}
    <form action="{% url 'cbt:submit_test' %}" method="post">
        {% csrf_token %}
        <input type="text" name="subject_title" id="subject_title" value="{{ subject }}" hidden>
        <input type="text" name="questions_count" id="questions_count" value="{{ questions_count }}" hidden>

        {% for question in questions.all %}
        <div class="card mb-2">
            <div class="card-body">
                <p class="card-text lead">{{ question.text}}</p>
                <div class="row">
                    <div class="col-6">
                        <div class="form-check">
                            <input
                                class="form-check-input"
                                type="radio"
                                id="{{ question.pk}} + A"
                                name="{{ question.text }}"
                                value="{{ question.option_a }}"
                            />
                            <label
                                for="{{ question.pk }} + A"
                                class="form-check-label"
                                >{{ question.option_a }}</label
                            >
                        </div>
                        <div class="form-check">
                            <input
                                class="form-check-input"
                                type="radio"
                                id="{{ question.pk}} + B"
                                name="{{ question.text }}"
                                value="{{ question.option_b }}"
                            />
                            <label
                                for="{{ question.pk }} + B"
                                class="form-check-label"
                                >{{ question.option_b }}</label
                            >
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-check">
                            <input
                                class="form-check-input"
                                type="radio"
                                id="{{ question.pk}} + C"
                                name="{{ question.text }}"
                                value="{{ question.option_c }}"
                            />
                            <label
                                for="{{ question.pk }} + C"
                                class="form-check-label"
                                >{{ question.option_c }}</label
                            >
                        </div>
                        <div class="form-check">
                            <input
                                class="form-check-input"
                                type="radio"
                                id="{{ question.pk}} + D"
                                name="{{ question.text }}"
                                value="{{ question.option_d }}"
                            />
                            <label
                                for="{{ question.pk }} + D"
                                class="form-check-label"
                                >{{ question.option_d }}</label
                            >
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

        <button type="submit" class="btn d-block m-auto btn-success ">Submit</button>
    </form>
    {% else %}
    <p>Sorry, No Test Available</p>

    {% endif %}
</div>
{% endblock content %}