CBTAPP/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('accounts.urls', namespace= 'accounts')),
    path('student/',include('student.urls', namespace='student')),
    path('lecturer/',include('lecturer.urls', namespace='lecturer')),
    path('test/', include('cbt.urls', namespace= 'cbt')),
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('', generalSignIn, name='signin'),
    path('create_student/', createStudent, name='create_student'),
    path('create_lecturer/', createLecturer, name='create_lecturer'),
    path('registrar/', registrarSignIn, name='registrar_signin'),
    path('registrar/dashboard/', registrarDashboard, name='registrar_dashboard'),
    path('create_subject/', createSubject, name="create_subject"),
    # path('student/signout/', studentSignOut, name = 'student_signout'),
    # path('student/register/', studentRegister, name = 'register_student'),
]

cbt/urls.py
from django.urls import path 
from .views import * 

app_name = 'cbt'

urlpatterns = [ 
    path('take_quiz/<int:pk>/', take_quiz, name = 'take_quiz'),
]

templates/registrar/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Registrar || Sign In</title>
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static '/css/registrar.css' %}" />
    <link rel="icon" href="{% static '/images/logo.png' %}" />
  </head>
  <body>
    <div class="overlay">{% block content %} {% endblock %}</div>

  </body>
</html>

templates/registrar/create.html
{% extends 'registrar/base.html' %} {% block content %} 
{% if form.matric_no %}
<form class="create-form" method="post" action="">
    <h2 class="text-center">Create Student</h2>
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{field.label_tag}} {{field}}
            </div>
        {% endfor %}
    <button type="submit" class="create-btn">Create</button>
</form>

{% else %}
<form class="create-form" method="post" action="">
    <h2 class="text-center">Create Lecturer</h2>
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6">
            {{ form.surname.label_tag }} {{ form.surname }}
        </div>
        <div class="col-md-6">{{ form.email.label_tag }} {{ form.email }}</div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{ form.first_name.label_tag }} {{ form.first_name }}
        </div>
        <div class="col-md-6">
            {{ form.subject.label_tag }} {{ form.subject }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{ form.other_name.label_tag }} {{ form.other_name }}
        </div>
    </div>
    <button type="submit" class="create-btn">Create</button>
</form>
{% endif %} {% endblock %}

templates/registrar/create_subject.html
{% extends 'registrar/base.html' %} {% block content %}

<form method="post">
  {% csrf_token %} {{form}}
  <button type="submit" class="btn btn-success">Create Subject</button>
</form>
{% endblock content %}

templates/registrar/dashboard.html
{% extends 'registrar/base.html' %} 

{% block content %} 
<header class="text-center">
    <h1>Welcome {{ user.username | capfirst}}</h1>
    <div>
        <a href="{% url 'accounts:create_student' %}" class="btn create-student-btn">Create Student </a>

        <a href="{% url 'accounts:create_lecturer' %}" class="btn create-lecturer-btn">Create Lecturer </a>
        <a href="{% url 'accounts:create_subject' %}"  class="btn btn-secondary">Create Subject</a>
    </div>
</header>
{% endblock %}

templates/registrar/signin.html
{% extends 'registrar/base.html' %} {% block content %}

<form method="post" action="" class="signin-form">
<h2 class="text-center">Sign In</h2>
    {% csrf_token %} {% for field in form %}
    <div class="form-group signin-form-group">
        {{ field.label_tag}} {{ field }} {{ field.errors }}
    </div>
    {% endfor %}
    <button type="submit" class="signin-btn">Sign In</button>
</form>
{% endblock %}