CBTAPP/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('accounts.urls', namespace= 'accounts')),
    path('student/',include('student.urls', namespace='student')),
    path('lecturer/',include('lecturer.urls', namespace='lecturer')),
    path('test/', include('cbt.urls', namespace= 'cbt')),
    path('admin/', admin.site.urls),
]

cbt/urls.py
from django.urls import path 
from .views import * 

app_name = 'cbt'

urlpatterns = [ 
    path('take_quiz/<int:pk>/', take_quiz, name = 'take_quiz'),
]

lecturer/urls.py
from django.urls import path
from .views import *


app_name = 'lecturer'

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('create_quiz/', create_quiz, name="create_quiz"),
    path('add_question/<int:pk>/', add_question, name="add_question"),
    path('view_exam/<int:pk>/', view_exam, name="view_exam"),
    path('view_quizzes/<str:subject_name>/', view_quzzes, name="view_quizzes"),
    path('add_students_to_quiz/<int:pk>/', add_students_to_quiz,
         name="add_students_to_quiz"),
         path('remove_student_from_quiz/<int:quizlist_id>/<int:student_id>/',remove_from_quiz, name="remove_from_quiz"),
]

lecturer/models.py
from django.db import models
from accounts.models import User

# Create your models here.


class Subject(models.Model):
    title = models.CharField(max_length=300)
    code = models.CharField(max_length=7)

    def __str__(self):
        return self.title


class Lecturer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    surname = models.CharField(max_length=25)
    email = models.EmailField()
    first_name = models.CharField(max_length=25)
    other_name = models.CharField(max_length=25)
    subject = models.OneToOneField(Subject, related_name='lecturer', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.surname} {self.first_name}"

lecturer/forms.py
from django.db import transaction

from django import forms 
from accounts.models import User
from .models import Lecturer,Subject

class LecturerCreationForm(forms.ModelForm):
    class Meta:
        model = Lecturer
        fields = ('surname','first_name', 'other_name','subject', 'email')
        widget = {
            'surname':forms.TextInput(attrs={'autocomplete':'off'}),
            'first_name':forms.TextInput(attrs={'autocomplete':'off'}),
            'other_name':forms.TextInput(attrs={'autocomplete':'off'}),
            'email':forms.TextInput(attrs={'autocomplete':'off'}),
        }

  

    @transaction.atomic
    def save(self):
        lecturer = super().save(commit=False)
        user = User.objects.create_user(username = self.cleaned_data.get('first_name'), email = self.cleaned_data.get('email'),type = 'lecturer', password = self.cleaned_data.get('surname'))
        user.save()
        lecturer.user = user 
        lecturer.subject = Subject.objects.get(title = self.cleaned_data.get('subject'))
        lecturer.save()
        

class SubjectCreationForm(forms.ModelForm):
    class Meta:
        model = Subject 
        fields = "__all__"

lecturer/views.py
from django.shortcuts import render, reverse, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
import logging

from .models import Lecturer, Subject
from cbt.models import TestResult, Quiz, Question, Option, QuizList
from cbt.forms import QuizCreationForm
from student.models import Student


logger = logging.getLogger('django')


@login_required
def dashboard(request):
    """     lecturer = Lecturer.objects.get(user=request.user)
        students = Subject.objects.get(
            title=lecturer.subject.title).students.all()
        subject = lecturer.subject
        test_results = TestResult.objects.filter(subject=subject)
        cascores = CAScore.objects.filter(subject=subject)
        exam_results = ExamResult.objects.filter(subject=subject)
        final_grades = FinalGrade.objects.filter(subject=subject)
        return render(request, 'lecturer/dashboard.html', {'lecturer': lecturer, 'students': students, 'subject': subject, 'test_results': test_results, 'cascores': cascores, 'exam_results': exam_results, 'final_grades': final_grades}) """
    lecturer = Lecturer.objects.get(user=request.user)
    subject_title = lecturer.subject.title
    students = Subject.objects.get(title=subject_title).students.all()
    # test_results = TestResult.objects.filter(subject__title=subject_title)

    return render(request, 'lecturer/dashboard.html', {'students': students, 'lecturer': lecturer})


@login_required
def create_quiz(request):
    form = QuizCreationForm()
    if request.method == 'POST':
        form = QuizCreationForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            lecturer = Lecturer.objects.get(user=request.user)
            quiz.subject = lecturer.subject
            quiz.save()
            quiz_list = QuizList(quiz=quiz)
            quiz_list.save()
            return redirect(reverse('lecturer:dashboard'))
    return render(request, 'lecturer/create_quizz.html', {'form': form})


@login_required
def view_quzzes(request, subject_name):
    subject = Subject.objects.get(title=subject_name)
    quizzes = Quiz.objects.filter(subject=subject)
    return render(request, 'lecturer/quizzes.html', {'quizzes': quizzes})


@login_required
def add_question(request, pk=0):
    if request.method == "POST":
        data = request.POST
        quiz = Quiz.objects.get(pk=pk)
        option_count = 1
        correct_option_no = 0
        question = None
        for x, y in data.items():
            if x == "csrfmiddlewaretoken":
                continue
            elif x == "question_text":
                question = Question(quiz=quiz, text=y)
                question.save()
            elif x == "correct_option_no":
                correct_option_no = int(y)
            else:
                option = Option(question=question, text=y, order=option_count)
                if correct_option_no == option_count:
                    option.is_correct = True
                option.save()
                option_count += 1
        return redirect(reverse("lecturer:dashboard"))
    elif request.method == 'GET':
        quiz = Quiz.objects.get(pk=pk)
        return render(request, "lecturer/set_questions.html", {'quiz': quiz})


@login_required
def view_exam(request, pk):
    quiz = None
    questions = None
    try:
        quiz = Quiz.objects.get(pk=pk)
        questions = Question.objects.filter(quiz=quiz)
    except:
        pass
    quiz_list = QuizList.objects.get(quiz=quiz)
    lecturer = Lecturer.objects.get(user=request.user)
    subject = lecturer.subject
    all_students = subject.students.all()
    non_candidates = []
    for student in all_students:
        if student in quiz_list.candidates.all():
            pass
        else:
            non_candidates.append(student)
    return render(request, 'lecturer/view_exam.html', {'quiz': quiz, 'questions': questions, 'non_candidates': non_candidates, 'quiz_list': quiz_list})


@login_required
def add_students_to_quiz(request, pk):
    if request.method == "POST":
        data = request.POST
        quiz = Quiz.objects.get(pk=pk)
        quiz_list = QuizList.objects.get(quiz=quiz)
        for x, y in data.items():
            if x == "csrfmiddlewaretoken":
                pass
            else:
                student = Student.objects.get(pk=int(y))
                quiz_list.candidates.add(student)
        return redirect(reverse("lecturer:view_exam", args=[pk]))


@login_required
def remove_from_quiz(request, quizlist_id, student_id):
    student = Student.objects.get(pk=student_id)
    quizlist = QuizList.objects.get(pk=quizlist_id)
    quizlist.candidates.remove(student)
    return redirect(reverse('lecturer:view_exam', args=[quizlist.quiz.pk]))

templates/lecturer/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=`, initial-scale=1.0" />
    <title>Lecturer || Dashboard</title>
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.css' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/base.css' %}"
    />
    <link
    rel="stylesheet"
    type="text/css"
    href="{% static '/css/forms.css' %}"
  />
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static '/css/layouts.css' %}"
  />
    <link rel="icon" href="{% static '/images/logo.png' %}" />
  </head>

  <body>
    <section class="row">
     
      <aside class="col-md-2 position-fixed aside">
        <ul class="side-nav__nav">
          <li>
            <a class="side-nav__link" href="{% url 'lecturer:dashboard' %}"
              >Dashboard</a
            >
          </li>
          <li>
            <a class="side-nav__link" href="{% url 'lecturer:create_quiz' %}" id="create_quiz-btn"
              >Create Quiz</a
            >
          </li>
          <li>
            <a class="side-nav__link" href="{% url 'lecturer:view_quizzes' request.user.lecturer.subject.title %}"
              >View Quizzes</a
            >
          </li>
        </ul>
      </aside>
      <main class="offset-md-2 col-md-10">
        <nav>
          <div>
            {% if lecturer.user.is_authenticated %}
            <h2>Welcome {{ lecturer.user.username }}</h2>
            {% endif %}
          </div>
        </nav>
        <div class="content">{% block content %} {% endblock content %}</div>
      </main>
    </section>
    <script src="{% static 'js/jquery-3.2.1.slim.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/set_questions.js' %}"></script>
    <script src="{% static 'js/view_exam.js' %}"></script>

    <script>
        const btn = document.querySelector("#create_quiz-btn")
        btn.addEventListener("click",function(e){
            if(quiz_exist){
                alert("Quiz Exist")
            }
        })
    </script>
  </body>
</html>

templates/lecturer/create_quizz.html
{% extends 'lecturer/base.html' %} 

{% block content %}
<h3>Create Exam Quiz</h3>
<form method="post" class="create_quiz_form">
  {% csrf_token %} {{form}}
  <button class="btn btn-success">Create Quiz</button>
</form>
{% endblock content%}

templates/lecturer/dashboard.html
{% extends 'lecturer/base.html' %} 

{% block content %}
<h3>Your Students</h3>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Matric No</th>
        {% comment %} <th>View Result</th> {% endcomment %}
    </tr>
    {% for student in students %} 
    <tr>
        <td>{{student}}</td>
        <td>{{student.matric_no}}</td>
        {% comment %} <td>
            {% if test_results %}
            {% for test_result in test_results %} 
                {% if test_result.student == student %}
                    {{ test_result.score }}
                {% else %} 
                    Not Taken Yet
                {% endif %}
            {% endfor %}
            {% else %}
            No Test Score
            {% endif %}

        </td> {% endcomment %}

       

    </tr>
        
    {% endfor %}
    
</table>


{% endblock content %}

templates/lecturer/quizzes.html
{% extends 'lecturer/base.html' %}

{% block content %}
    <h3>Your Quizzes</h3>
    {% if quizzes %}
    <div class="quizzes_container">
        {% for quiz in quizzes %}
        <div class="card p-5">
            <h4>{{quiz.title}}</h4>
            <p>{{quiz.description}}</p>
            <a href="{% url 'lecturer:view_exam' quiz.pk %}" class="btn btn-success view_quiz_btn">View Quiz</a>
        </div>
    
        {% endfor %}
    </div>
      
    {% endif %}
{% endblock content %}

templates/lecturer/set_questions.html
{% extends 'lecturer/base.html' %} {% block content %}
<h3>Enter Question</h3>
<form method="post" action="{% url 'lecturer:add_question' quiz.pk %}">
  {% csrf_token %}
  <div class="form-group">
    <label for="question_text">Enter Question</label>
    <textarea
      id="question_text"
      name="question_text"
      class="form-control"
    ></textarea>
  </div>
  <label for="correct_option_no">Enter Correct option No:</label>
  <input
    type="number"
    name="correct_option_no"
    id="correct_option_no"
    class="form-control"
  />
  <button class="btn btn-secondary" id="add-options-btn">Add Options</button>

  <div class="options-container my-3"></div>
  <button type="submit" class="btn btn-success">Add Question</button>
  <a href="#" class="btn btn-secondary">Finish Questions</a>
</form>

{% endblock content %}

templates/lecturer/view_exam.html
{% extends 'lecturer/base.html' %} {% block content %}

<div>
  <h3>{{quiz.title}}</h3>
  <p>{{quiz.description}}</p>
  {% comment %} <a href="{% url 'lecturer:add_question' quiz.pk %}" class="btn btn-success">
    Add Question</a
  >
  <div>
    
  </div> {% endcomment %}

  <div class="tabs">
    <a href="#" class="tab-btn question-btn  active">Questions</a>
    <a href="#" class="tab-btn candidate-btn">Quiz Candidates</a>
  </div>
  <div class="tab-container">
      
      <div class="questions_container shown">
        <div>
          <a href="{% url 'lecturer:add_question' quiz.pk%}" class="btn btn-success">Add Questions</a>
        </div>
        {% if questions %}
          {% for question in questions %}
            <p>{{ question.text}}</p>
            <a href="#" class="btn btn-success">Edit Question</a>
          {% endfor %} 
        {% else %}
          <p>No questions available</p>
        {% endif %}
      </div>
  
      <div class="candidates_container">
        <button type="button" data-toggle="modal" data-target="#addStudentsModal" class="btn btn-warning">Add Students to quiz</button>
        {% if quiz_list.candidates.all %}

        <table class="table table-striped">
          <thead>
            <tr>
              <th>Student's Names</th>
              <th>Quiz Score</th>
              <th>Remove From Quiz</th>
            </tr>
          </thead>
          {% for student in quiz_list.candidates.all %}
            <tr>
              <td>{{student.surname}} {{student.first_name}} {{student.other_name}}
              </td>
              <td>
                {% if student.quiz_results.all.count > 0 %}
                  {% for quiz_result in student.quiz_results.all %}
                    {% if quiz_result.quiz == quiz %}
                      {{quiz_result.score}}
                    {% endif %}
                  {% endfor %}
                {% endif %}
               </td>
               <td>
                {% if student.quiz_results.all.count > 0 %}
                  {% for quiz_result in student.quiz_results.all %}
                    {% if quiz_result.quiz == quiz %}
                      Not Allowed
                    
                    {% endif %}
                  {% endfor %}
                  {% else %}
                    <a href="{% url 'lecturer:remove_from_quiz' quizlist_id=quiz_list.pk student_id=student.pk %}" class="btn btn-secondary"> Remove From Quiz</a>
                {% endif %}
               </td>
                
            </tr>
          
          {% endfor %}
        </table> 
        {% else %}  
          <p>No Candidates available<p>
        {% endif %}
      </div>
      
  </div>

  
</div>


<div class="modal fade" id="addStudentsModal" tabindex="-1" role="dialog" aria-labelledby="addStudentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addStudentModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'lecturer:add_students_to_quiz' quiz.pk %}">
           {% csrf_token %}
          {% for student in non_candidates %}
          <div>
            <h5>{{student.surname}} {{student.first_name}} {{student.other_name}}</h5>
            <input type="checkbox" name="studentsid" value="{{student.pk}}" >
          </div>
          
        {% endfor %}
        <button type="submit" class="btn btn-secondary">Submit</button>
        </form>
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

templates/lecturer/view_student.html
{% extends 'lecturer/base.html' %} 

{% block content %} 
    <h1>{{ student.user.username }}</h1>
{% endblock content %}